In [1]:
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
from kamo.atom_properties.k39 import Potassium39
%matplotlib inline

%load_ext autoreload
%autoreload 2

atom = Potassium39()

plt.rcParams['figure.dpi'] = 200

In [2]:
from kexp.calibrations.magnets import (magnetic_field_to_i_transducer, i_transducer_to_magnetic_field)

Outer coil current <--> Magnetic field

In [3]:
magnetic_field_to_i_transducer(551.)

np.float64(197.38291932905088)

In [4]:
i_transducer_to_magnetic_field(182.)

np.float64(508.0224877531497)

Compute ground state microwave transitions

In [5]:
# what magnetic field?
b=60.01

# initial and final states

F_i = 1
mf_i = -1

F_f = 1
mf_f = 0

# print(abs(k.get_microwave_transition_frequency(4,0,.5,F_i,mf_i,F_f,mf_f,B=b)))

Get scattering lengths

In [13]:
f = 1
mf = -1

atom.get_scattering_length(f,mf,505.)

np.float64(0.28803314348071785)

In [7]:
np.diff(atom.get_magnetic_field_from_ground_state_transition_frequency(1,-1,2,-2,[147.2583e6,147.2586e6])) * 1.e3

array([-4.37026852])

In [8]:
from kexp.config import ExptParams
p = ExptParams()
f_f1m1_f2m2_meas = p.frequency_raman_transition
b = atom.get_magnetic_field_from_ground_state_transition_frequency(2,-2,1,-1,f_f1m1_f2m2_meas)
print(b)
f_f1m1_f2m2 = atom.get_ground_state_transition_frequency(2,-2,1,-1,B=b)
f_f1m1_f10 = atom.get_ground_state_transition_frequency(1,-1,1,0,B=b)
f_f10_f11 = atom.get_ground_state_transition_frequency(1,0,1,1,B=b)
print(f_f1m1_f2m2, f_f1m1_f10, f_f10_f11)

ValueError: One or more transition frequencies correspond with one of the bounds of the magnetic field specified in the 'B_bounds_G' argument. Update this argument and re-run.

In [ ]:
atom.get_ground_state_transition_sensitivity(1,-1,2,-2,B=b)

array([-0.06856133])

In [ ]:
atom.get_ground_state_transition_sensitivity(1,-1,1,0,B=b)

array([0.00372274])