In [2]:
import numpy as np

# Create an examplse 4D array
arr = np.random.rand(3, 4, 5, 6)

# Specify the dimensions to slice
# For example, if we want to slice out a 2D array from dimensions (1, 2) in the 4D array
slice_dims = (1, slice(None), 3)  # (dimension_index_to_slice, slice_expression, dimension_index_to_slice)

# Create a slicing tuple for the array
slicing_tuple = tuple(slice(None) if i not in slice_dims else slice_dims[slice_dims.index(i)] for i in range(arr.ndim))
print(slicing_tuple)
# Extract the 2D slice
result = arr[slicing_tuple]

print("Resulting shape:", result.shape)
print("Resulting array:\n", result)


(slice(None, None, None), 1, slice(None, None, None), 3)
Resulting shape: (3, 5)
Resulting array:
 [[0.18568613 0.72604743 0.00254518 0.2085948  0.08731132]
 [0.19466985 0.46266217 0.89985306 0.23928318 0.50088042]
 [0.29769219 0.01488556 0.75017604 0.36908707 0.46691284]]
